name: Run Python Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Run compile.sh
      run: |
        chmod +x ./compile.sh
        echo -e "Aditya Budhwar" | ./compile.sh
